### ISSUE TITLE
Remove automatic NSString-to-str conversion

### ISSUE THREAD

**Issue by dgelessus** [pybee/rubicon-objc#101]
As [discussed on Gitter](https://gitter.im/pybee/general?at=5a767662e217167e2c3c2d53), this behavior is problematic when you want to create a new `NSString` using a factory or init method, or when you want to call methods on a `NSString` returned from a method.

Instead, an `ObjCStringInstance` class should be added, which adds a Pythonic interface to `NSString` objects.

**Comment by cculianu** [comment]
At the risk of sounding like a troll, I did also notice this but my reaction was "good riddance. Python string ops are much nicer to work with than NSSString".  :)

That being said -- I hope whatever enhancement happens also leaves the option around to keep the python string<->NSString transparency going since it makes writing lots of code that sets NSString properties on objc objects in Python a breeze to write.  Having to put NSString.stringWithWhatever_(b'somedata') would suck.  :)

**Comment by freakboy3742** [comment]
@dgelessus Sounds reasonable to me.

**Comment by dgelessus** [comment]
@cculianu Converting `str` from and to `NSString` is already quite easy even without automatic conversion - you can use `str(nsstring)` to convert a `NSString` to a Python `str` by hand, and `at(pystring)` to create a `NSString` from a `str`.

Also, I think the automatic conversion *to* `NSString` will probably stay, i. e. you'll still be able to pass Python strings into Objective-C methods and they will be converted automatically. The only change will be that if a `NSString` is *returned* from a method, you now need an explicit `str` call to convert it to a Python string. And since there's going to be an `ObjCStringInstance` class that provides Pythonic operations on `NSString`s, you shouldn't need to convert to `str` for simple operations like slicing the string.

**Comment by cculianu** [comment]
Wow.  That sounds like the best of all worlds.  Pretty badass.  I like it! 👍
