### ISSUE TITLE
ObjCStrInstance isn't as string-like as the Python standard library sometimes requires

### ISSUE THREAD

**Issue by freakboy3742** [pybee/rubicon-objc#115]
The recent change (#110) to use ObjCStrInstance instead of automated str conversion has introduced some incompatibilities in Toga. 

I've found two examples so far, but they're in a similar class of usage:
* `Decimal(s)`
* `os.path.dirname(s)`

Both fail with an error that the argument isn't a string or bytes. It's easy enough to work around - you just force the conversion with `str()`. However, given it's a relatively common use case, it would be nice to either (a) provide a workaround that does allows "as str" conversion to be done automatically, or (b) add this to the list of workarounds you're likely to need to use when dealing with objects returned by an ObjC method.

**Comment by dgelessus** [comment]
I don't think we can really do anything in the case of `Decimal`, because its constructor explicitly checks if the argument is a `str` object, which our `ObjCStrInstance` isn't. The only solution there is to add an explicit `str` call.

The `os.path.dirname` case could perhaps be improved. On Python 3.5 and earlier `dirname` is duck-typed, so it should be enough to add the missing methods to `ObjCStrInstance` (in this case `rstrip`, as far as I can tell). On Python 3.6 and later `dirname` uses `os.fspath` to convert the argument (and so do all other `os.path` functions), so we could implement `__fspath__` on `ObjCStrInstance` to make that work. This would allow using ObjC strings as paths in other places as well (such as `open`) - but since that would only work on Python 3.6 and later, users would still need to add explicit `str` conversions for it to work consistently on all Python versions...

**Comment by freakboy3742** [comment]
Yeah - I couldn't think of an obvious way to fix the Decimal case, either. Adding `__fspath__` is an easy win, though; I've just added that to #116.

**Comment by CookBob** [comment]
Should the str() addition be in the startup method in the app's class, or in the numberinput.py file in toga's widgets directory?

**Comment by freakboy3742** [comment]
@CookBob The problem you describe is related to Toga's usage of Rubicon, rather than Rubicon itself, so that's a better place to track these problems. 

I've already made a bunch of changes to Toga applying str() calls where necessary, but it's entirely possible I've missed some; so feel free to submit an issue (or PR) fixing the problem. 

As for the right place for the fix - that depends a bit on the specific problem. It's not entirely clear from your comment what problem you're seeing (and where); but the conversion should generally be applied a soon as an ObjCStrInstance is received via a callback/API call in Python space.
