### ISSUE TITLE
Things with the name objc

### ISSUE THREAD

**Issue by dgelessus** [pybee/rubicon-objc#21]
Currently there are three things in `rubicon.objc` that have the name `objc`:

* The `rubicon.objc` package
* The `objc` module inside the `rubicon.objc` package
* The `objc` `CDLL` library inside the `objc` module

This would normally be okay, as most people probably only use the `rubicon.objc` package. However `rubicon.objc`'s `__init__.py` imports the `objc` `CDLL` from the `objc` module. This hides the `rubicon.objc.objc` module, which cannot be accessed at all from outside. (The name `rubicon.objc.objc` corresponds to the `CDLL`, not the module.) Not all names from the `rubicon.objc.objc` module are imported into the `rubicon.objc` package, so it is sometimes necessary to access the module (for example when debugging).

To resolve this, either the module or the `CDLL` could be renamed. Renaming the module would be fully backwards-compatible, as the module was never accessible by its name before. The `CDLL` is accessible from outside, so renaming it would break any code that uses it.

**Comment by freakboy3742** [comment]
There are two hard problems in computer science... cache invalidation, naming things, and off-by-one errors...

:-)

I agree with your analysis; my inclination would be to rename the `obj.py` module to `language.py` or `runtime.py`. If you've got a better suggestion, let me know - I'm not mortally attached to either name, and as you point out, the name isn't publicly visible.

The other option that is on the table, and one that I've considered, is to *remove* the intermediate `objc` module - effectively rename the whole projects a Rubicon, not Rubicon-objc. The separation existed because at one point, I was also maintaining Rubicon-java, in anticipation of Android support. However, it turns out that project was a dead end, and the extra layer of namespace isn't needed.

This would obviously be backwards incompatible; but would vastly simplify the process of talking about Rubicon as a project. I'd be interested in your thoughts on whether this is worthwhile.

As a side note - you've been making some amazing contributions to Rubicon over the last couple of months - Do you have any interest in joining the project as a maintainer? If you do, drop me an email at russell@keith-magee.com. No pressure, though - If you keep submitting high quality patches, I'm happy to keep merging them :-)

**Comment by dgelessus** [comment]
`runtime.py` sounds good to me, it also matches the C header `<objc/runtime.h>` that defines the runtime API. And it's certainly better than any of the names I could think of.

I don't have any real preference on whether the `rubicon.objc` sub-namespace should be kept or removed. On one hand it's a nice descriptive name and the `rubicon` namespace could be used for other things, but a shorter name is quicker to type (especially for people like me who prefer to use fully qualified names instead of `from`-`import`s).

If you do decide to remove the intermediate `rubicon.objc` module, that could be done in a backwards-compatible way I think. Something like:

* Move all modules from `rubicon.objc` to `rubicon`
* Rename the former `rubicon.objc.objc` module to `rubicon.runtime`
* In the `runtime` module, rename the `objc` `CDLL` to `libobjc` (or something else)
* Recreate the `objc` package with `__init__.py`, `core_foundation.py`, `objc.py` and `types.py` as before, which `from`-`import` all necessary names from the new locations (and import `rubicon.runtime.libobjc` as `objc` for compatibility).

**Comment by freakboy3742** [comment]
Ok - Executive decision time. 

On the off chance that we ever *do* need another language bridge (Go? Rust?), lets rename `rubicon.objc.objc` to `rubicon.objc.runtime`, and prefix the two `CDLL` references in `runtime.py` with `lib`.

**Comment by dgelessus** [comment]
Sounds good. For short imports without using `from`-`import *`, I've found that `from rubicon import objc` works quite well, so I'd be fine with keeping the intermediate `objc` namespace.

As for extra languages that could be bridged, Swift would be a likely candidate, especially because I think Apple's long-term plan is to deprecate Objective-C completely.

**Comment by freakboy3742** [comment]
Fixed in a9ed8df10 (but referenced the wrong issue...)
