### ISSUE TITLE
0.2.6 issues

### ISSUE THREAD

**Issue by glasnt** [pybee/rubicon-objc#40]
Running Sierra, xCode 8.3

Running the [Briefcase Tutorial 2](https://github.com/pybee/briefcase/blob/50d0597d5f10789645b6822d51bf5cddefaf36ad/docs/tutorials/tutorial-1.rst), using toga 0.2.8, and rubicon-objc 0.2.6

```
$ python -m appname
Traceback (most recent call last):
  File "/Users/kmclaughlin/.pyenv/versions/3.5.1/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/kmclaughlin/.pyenv/versions/3.5.1/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/kmclaughlin/git/pybee/tutorial1/appname/appname/__main__.py", line 4, in <module>
    main().main_loop()
  File "/Users/kmclaughlin/git/pybee/tutorial1/venv/lib/python3.5/site-packages/toga_cocoa/app.py", line 137, in main_loop
    self._startup()
  File "/Users/kmclaughlin/git/pybee/tutorial1/venv/lib/python3.5/site-packages/toga_cocoa/app.py", line 89, in _startup
    self.resource_path = os.path.dirname(os.path.dirname(NSBundle.mainBundle().bundlePath))
TypeError: 'ObjCInstance' object is not callable
```

Substituting out rubicon for the version that was up yesterday, 0.2.4 (0.2.5 may have been skipped?)

```
$ pip install rubicon-objc==0.2.4
$ python -m appname
```

Gives me a valid f2c

**Comment by glasnt** [comment]
As a note, for now, 0.2.4 works for me in that specific example

**Comment by glasnt** [comment]
And yet strangely, https://travis-ci.org/pybee/rubicon-objc/builds/224819886 is fine

**Comment by freakboy3742** [comment]
Weirdly, I *don't* see this using 0.2.6 on El Cap. 

@dgelessus Have you got any ideas?

**Comment by dgelessus** [comment]
Argh, it's another case of a method being changed to a property. In 10.11 (El Capitan), `+[NSBundle mainBundle]` is still a regular method. In 10.12 (Sierra), class properties were added, and `NSBundle.mainBundle` is now a class property. That means in 10.11, you *must* have the parentheses in `NSBundle.mainBundle()`, and in 10.12, you *must not* have them in `NSBundle.mainBundle`. (The reason why Apple can convert methods to properties like this is that in Objective-C it's not a breaking change - the method is called with `[NSBundle mainBundle]`, and the property is accessed with `NSBundle.mainBundle`.)

The standard workaround for this is to use `send_message(ObjCClass("NSBundle"), "mainBundle")`, which works the same way regardless of whether `mainBundle` is a property or not.

**Comment by glasnt** [comment]
> 10.11
> 10.12
> not a breaking change

😡

Thanks for the look-in, @dgelessus. Reckon we can handle both cases transparently? As I mentioned above, I'm still using 0.2.4 locally.

**Comment by dgelessus** [comment]
To be fair, Apple did nothing wrong. The issue is that Objective-C has two syntaxes (method calling with `[object name]`, and property access with `object.name`), and rubicon-objc maps both of them to Python attribute access. When there's both a property and a method with the same name, rubicon-objc prefers the property. That means that if there's a method called `name`, and in a future version a property called `name` is added, the meaning of `object.name` in rubicon-objc suddenly changes. However in Objective-C that change doesn't affect existing programs, because the `[object name]` syntax still works, even if `name` is also a property.

To fix this, we would need to make attribute access not ambiguous, i. e. make it work *only* for properties or *only* for methods. We *could* completely remove support for properties, then you'd always need to call getters and setters by hand. Or we could make attribute access only work for properties, but then we'd need a new syntax for calling methods, and it wouldn't actually solve the problem (it would only mean that you get an `AttributeError` on 10.11 instead of silently different behavior). Both options aren't great, but neither is the current workaround via `send_message`...

**Comment by freakboy3742** [comment]
Ok - I've got a working test case for this problem now. Working on a fix.

**Comment by alkopop79** [comment]
I still get error (Mac OS X High Sierra). It seems `miniconda` messes things up:

```
Traceback (most recent call last):
  File "/Users/alkopop79/miniconda3/bin/toga-demo", line 11, in <module>
    sys.exit(run())
  File "/Users/alkopop79/miniconda3/lib/python3.6/site-packages/toga_demo/__main__.py", line 5, in run
    main().main_loop()
  File "/Users/alkopop79/miniconda3/lib/python3.6/site-packages/toga_cocoa-0.2.15-py3.6.egg/toga_cocoa/app.py", line 167, in main_loop
  File "/Users/alkopop79/miniconda3/lib/python3.6/site-packages/toga_cocoa-0.2.15-py3.6.egg/toga_cocoa/app.py", line 95, in _startup
TypeError: 'ObjCInstance' object is not callable
```

**Comment by dgelessus** [comment]
@alkopop79 As far as I know, that's an issue in Toga caused by High Sierra. Miniconda *shouldn't* have anything to do with it. See pybee/toga#243.
