### ISSUE TITLE
Property falsely returns Method insted of int

### ISSUE THREAD

**Issue by Ocupe** [pybee/rubicon-objc#46]
The Problem happens in the header of the for loop at ```filenames.count``` (in the following code). When looking into the [docs](https://developer.apple.com/reference/foundation/nsarray/1409982-count?changes=latest_minor&language=objc) I see that ```count``` is a property but it's returning a method at the moment. ```filenames``` is a  ```<__NSSingleObjectArrayI 0x100868e30>```. I think this problem is related to https://github.com/pybee/rubicon-objc/issues/30 but I'm not sure how to fix it.

~~~python
 @objc_method
    def application_openFiles_(self, app, filenames) -> None:
        //print("open file ", filenames)
        for i in range(0, filenames.count):
            filename = filenames.objectAtIndex(i)
            if isinstance(filename, str):
                fileURL = NSURL.fileURLWithPath(filename)
~~~
this is the error log:
~~~
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/Users/Jonas/Documents/Programming/PyBee/rubicon-objc/rubicon/objc/objc.py", line 1069, in _objc_method
    result = f(py_self, *args)
  File "/Users/Jonas/Documents/Programming/PyBee/toga/src/cocoa/toga_cocoa/app.py", line 53, in application_openFiles_
    for i in range(0, filenames.count):
TypeError: 'method' object cannot be interpreted as an integer
~~~

**Comment by dgelessus** [comment]
You are right, there were some changes to how properties work (see #41), which means that if you want to use a property directly (without calling it like a method), you need to declare it first using `ObjCClass.declare_property`.

However that's not the reason why you're getting this error, and `declare_property` won't help here. `count` is always a method because of #42, which added special cases to make `NSArray` and `NSDictionary` work like Python `list` and `dict`. We had a small name conflict there, because there is a `count` method on Python `list` and Objective-C `NSArray`, but the two do different things. In the end, we [decided](https://github.com/pybee/rubicon-objc/pull/42#pullrequestreview-39615819) to make `count` on `NSArray`s work like Python `list.count`. That means to get the length of a `NSArray`, you need to use `len` like with a Python list, instead of the `count` method.

**Comment by Ocupe** [comment]
Thank you for the inside @dgelessus. I tried ```len()``` and it worked but I didn't know if it was an accident or if it was designed to work. Now I know! I used it to fix https://github.com/pybee/toga/pull/171.
